# Traefik Dynamic Configuration

http:
  # Define middleware for protocol conversion
  middlewares:
    protocol-converter:
      forwardAuth:
        address: "http://protocol-converter:3000/convert"
        trustForwardHeader: true

  # Define routers and services (additional to Docker provider)
  routers:
    # Router for GraphQL to REST conversion
    graphql-to-rest:
      rule: "Path(`/convert/graphql-to-rest`)"
      service: "protocol-converter"
      middlewares:
        - "protocol-converter"
      
    # Router for Claimant Services GraphQL API
    claimant-graphql:
      rule: "Path(`/graphql`)"
      service: "claimant-services"
      
    # Router for Claims Processing REST API
    claims-api:
      rule: "PathPrefix(`/api/claims`)"
      service: "claims-processing"
      
    # Router for Claimant UI
    claimant-ui:
      rule: "PathPrefix(`/claimant`)"
      service: "claimant-ui"
    
    # Router for Claims Processing UI
    claims-ui:
      rule: "PathPrefix(`/processor`)"
      service: "claims-ui"
    
    # Router for API Gateway Dashboard
    gateway-dashboard:
      rule: "PathPrefix(`/gateway-dashboard`)"
      service: "gateway-dashboard"
    
    # Router for Main UI
    ui:
      rule: "PathPrefix(`/`)"
      service: "ui-demo"

  # Define services (additional to Docker provider)
  services:
    protocol-converter:
      loadBalancer:
        servers:
          - url: "http://protocol-converter:3000"
    
    claimant-services:
      loadBalancer:
        servers:
          - url: "http://claimant-services:4000"
    
    claims-processing:
      loadBalancer:
        servers:
          - url: "http://claims-processing:8000"
    
    claimant-ui:
      loadBalancer:
        servers:
          - url: "http://claimant-ui:80"
    
    claims-ui:
      loadBalancer:
        servers:
          - url: "http://claims-ui:80"
    
    gateway-dashboard:
      loadBalancer:
        servers:
          - url: "http://gateway-dashboard:80"
    
    ui-demo:
      loadBalancer:
        servers:
          - url: "http://ui-demo:80"