// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: payment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Service Registration Messages
type RegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceId      string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Technology     string                 `protobuf:"bytes,3,opt,name=technology,proto3" json:"technology,omitempty"`
	Protocol       string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Endpoint       string                 `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	HealthEndpoint string                 `protobuf:"bytes,6,opt,name=health_endpoint,json=healthEndpoint,proto3" json:"health_endpoint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetTechnology() string {
	if x != nil {
		return x.Technology
	}
	return ""
}

func (x *RegisterRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RegisterRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterRequest) GetHealthEndpoint() string {
	if x != nil {
		return x.HealthEndpoint
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Heartbeat Messages
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Claims Query Messages
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *StatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Claim struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ClaimReferenceId      string                 `protobuf:"bytes,1,opt,name=claim_reference_id,json=claimReferenceId,proto3" json:"claim_reference_id,omitempty"`
	FirstName             string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName              string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	EmailAddress          string                 `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	PhoneNumber           string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	EmployerName          string                 `protobuf:"bytes,6,opt,name=employer_name,json=employerName,proto3" json:"employer_name,omitempty"`
	EmployerId            string                 `protobuf:"bytes,7,opt,name=employer_id,json=employerId,proto3" json:"employer_id,omitempty"`
	EmploymentStartDate   string                 `protobuf:"bytes,8,opt,name=employment_start_date,json=employmentStartDate,proto3" json:"employment_start_date,omitempty"`
	EmploymentEndDate     string                 `protobuf:"bytes,9,opt,name=employment_end_date,json=employmentEndDate,proto3" json:"employment_end_date,omitempty"`
	TotalAnnualEarnings   float64                `protobuf:"fixed64,10,opt,name=total_annual_earnings,json=totalAnnualEarnings,proto3" json:"total_annual_earnings,omitempty"`
	SeparationReasonCode  string                 `protobuf:"bytes,11,opt,name=separation_reason_code,json=separationReasonCode,proto3" json:"separation_reason_code,omitempty"`
	SeparationExplanation string                 `protobuf:"bytes,12,opt,name=separation_explanation,json=separationExplanation,proto3" json:"separation_explanation,omitempty"`
	StatusCode            string                 `protobuf:"bytes,13,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReceivedTimestamp     string                 `protobuf:"bytes,14,opt,name=received_timestamp,json=receivedTimestamp,proto3" json:"received_timestamp,omitempty"`
	StateTaxAmount        float64                `protobuf:"fixed64,15,opt,name=state_tax_amount,json=stateTaxAmount,proto3" json:"state_tax_amount,omitempty"`
	FederalTaxAmount      float64                `protobuf:"fixed64,16,opt,name=federal_tax_amount,json=federalTaxAmount,proto3" json:"federal_tax_amount,omitempty"`
	TotalTaxAmount        float64                `protobuf:"fixed64,17,opt,name=total_tax_amount,json=totalTaxAmount,proto3" json:"total_tax_amount,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Claim) Reset() {
	*x = Claim{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim) ProtoMessage() {}

func (x *Claim) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim.ProtoReflect.Descriptor instead.
func (*Claim) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *Claim) GetClaimReferenceId() string {
	if x != nil {
		return x.ClaimReferenceId
	}
	return ""
}

func (x *Claim) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Claim) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Claim) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *Claim) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Claim) GetEmployerName() string {
	if x != nil {
		return x.EmployerName
	}
	return ""
}

func (x *Claim) GetEmployerId() string {
	if x != nil {
		return x.EmployerId
	}
	return ""
}

func (x *Claim) GetEmploymentStartDate() string {
	if x != nil {
		return x.EmploymentStartDate
	}
	return ""
}

func (x *Claim) GetEmploymentEndDate() string {
	if x != nil {
		return x.EmploymentEndDate
	}
	return ""
}

func (x *Claim) GetTotalAnnualEarnings() float64 {
	if x != nil {
		return x.TotalAnnualEarnings
	}
	return 0
}

func (x *Claim) GetSeparationReasonCode() string {
	if x != nil {
		return x.SeparationReasonCode
	}
	return ""
}

func (x *Claim) GetSeparationExplanation() string {
	if x != nil {
		return x.SeparationExplanation
	}
	return ""
}

func (x *Claim) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *Claim) GetReceivedTimestamp() string {
	if x != nil {
		return x.ReceivedTimestamp
	}
	return ""
}

func (x *Claim) GetStateTaxAmount() float64 {
	if x != nil {
		return x.StateTaxAmount
	}
	return 0
}

func (x *Claim) GetFederalTaxAmount() float64 {
	if x != nil {
		return x.FederalTaxAmount
	}
	return 0
}

func (x *Claim) GetTotalTaxAmount() float64 {
	if x != nil {
		return x.TotalTaxAmount
	}
	return 0
}

type ClaimsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        []*Claim               `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimsResponse) Reset() {
	*x = ClaimsResponse{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimsResponse) ProtoMessage() {}

func (x *ClaimsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimsResponse.ProtoReflect.Descriptor instead.
func (*ClaimsResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimsResponse) GetClaims() []*Claim {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *ClaimsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClaimsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Payment Update Messages
type PaymentUpdateRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ClaimId             string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	WeeklyBenefitAmount float64                `protobuf:"fixed64,3,opt,name=weekly_benefit_amount,json=weeklyBenefitAmount,proto3" json:"weekly_benefit_amount,omitempty"`
	MaximumBenefit      float64                `protobuf:"fixed64,4,opt,name=maximum_benefit,json=maximumBenefit,proto3" json:"maximum_benefit,omitempty"`
	FirstPaymentAmount  float64                `protobuf:"fixed64,5,opt,name=first_payment_amount,json=firstPaymentAmount,proto3" json:"first_payment_amount,omitempty"`
	UpdatedBy           string                 `protobuf:"bytes,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Notes               string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PaymentUpdateRequest) Reset() {
	*x = PaymentUpdateRequest{}
	mi := &file_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentUpdateRequest) ProtoMessage() {}

func (x *PaymentUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentUpdateRequest.ProtoReflect.Descriptor instead.
func (*PaymentUpdateRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentUpdateRequest) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *PaymentUpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentUpdateRequest) GetWeeklyBenefitAmount() float64 {
	if x != nil {
		return x.WeeklyBenefitAmount
	}
	return 0
}

func (x *PaymentUpdateRequest) GetMaximumBenefit() float64 {
	if x != nil {
		return x.MaximumBenefit
	}
	return 0
}

func (x *PaymentUpdateRequest) GetFirstPaymentAmount() float64 {
	if x != nil {
		return x.FirstPaymentAmount
	}
	return 0
}

func (x *PaymentUpdateRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *PaymentUpdateRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type PaymentUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentUpdateResponse) Reset() {
	*x = PaymentUpdateResponse{}
	mi := &file_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentUpdateResponse) ProtoMessage() {}

func (x *PaymentUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentUpdateResponse.ProtoReflect.Descriptor instead.
func (*PaymentUpdateResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PaymentUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\"\xc5\x01\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"technology\x18\x03 \x01(\tR\n" +
	"technology\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x1a\n" +
	"\bendpoint\x18\x05 \x01(\tR\bendpoint\x12'\n" +
	"\x0fhealth_endpoint\x18\x06 \x01(\tR\x0ehealthEndpoint\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"g\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"G\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"'\n" +
	"\rStatusRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xd6\x05\n" +
	"\x05Claim\x12,\n" +
	"\x12claim_reference_id\x18\x01 \x01(\tR\x10claimReferenceId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12#\n" +
	"\remail_address\x18\x04 \x01(\tR\femailAddress\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12#\n" +
	"\remployer_name\x18\x06 \x01(\tR\femployerName\x12\x1f\n" +
	"\vemployer_id\x18\a \x01(\tR\n" +
	"employerId\x122\n" +
	"\x15employment_start_date\x18\b \x01(\tR\x13employmentStartDate\x12.\n" +
	"\x13employment_end_date\x18\t \x01(\tR\x11employmentEndDate\x122\n" +
	"\x15total_annual_earnings\x18\n" +
	" \x01(\x01R\x13totalAnnualEarnings\x124\n" +
	"\x16separation_reason_code\x18\v \x01(\tR\x14separationReasonCode\x125\n" +
	"\x16separation_explanation\x18\f \x01(\tR\x15separationExplanation\x12\x1f\n" +
	"\vstatus_code\x18\r \x01(\tR\n" +
	"statusCode\x12-\n" +
	"\x12received_timestamp\x18\x0e \x01(\tR\x11receivedTimestamp\x12(\n" +
	"\x10state_tax_amount\x18\x0f \x01(\x01R\x0estateTaxAmount\x12,\n" +
	"\x12federal_tax_amount\x18\x10 \x01(\x01R\x10federalTaxAmount\x12(\n" +
	"\x10total_tax_amount\x18\x11 \x01(\x01R\x0etotalTaxAmount\"l\n" +
	"\x0eClaimsResponse\x12&\n" +
	"\x06claims\x18\x01 \x03(\v2\x0e.payment.ClaimR\x06claims\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8d\x02\n" +
	"\x14PaymentUpdateRequest\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x122\n" +
	"\x15weekly_benefit_amount\x18\x03 \x01(\x01R\x13weeklyBenefitAmount\x12'\n" +
	"\x0fmaximum_benefit\x18\x04 \x01(\x01R\x0emaximumBenefit\x120\n" +
	"\x14first_payment_amount\x18\x05 \x01(\x01R\x12firstPaymentAmount\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x06 \x01(\tR\tupdatedBy\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\"K\n" +
	"\x15PaymentUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xbb\x02\n" +
	"\x0ePaymentService\x12F\n" +
	"\x0fRegisterService\x12\x18.payment.RegisterRequest\x1a\x19.payment.RegisterResponse\x12F\n" +
	"\rSendHeartbeat\x12\x19.payment.HeartbeatRequest\x1a\x1a.payment.HeartbeatResponse\x12D\n" +
	"\x11GetClaimsByStatus\x12\x16.payment.StatusRequest\x1a\x17.payment.ClaimsResponse\x12S\n" +
	"\x12UpdateClaimPayment\x12\x1d.payment.PaymentUpdateRequest\x1a\x1e.payment.PaymentUpdateResponseB\tZ\a./protob\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_payment_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: payment.RegisterRequest
	(*RegisterResponse)(nil),      // 1: payment.RegisterResponse
	(*HeartbeatRequest)(nil),      // 2: payment.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 3: payment.HeartbeatResponse
	(*StatusRequest)(nil),         // 4: payment.StatusRequest
	(*Claim)(nil),                 // 5: payment.Claim
	(*ClaimsResponse)(nil),        // 6: payment.ClaimsResponse
	(*PaymentUpdateRequest)(nil),  // 7: payment.PaymentUpdateRequest
	(*PaymentUpdateResponse)(nil), // 8: payment.PaymentUpdateResponse
}
var file_payment_proto_depIdxs = []int32{
	5, // 0: payment.ClaimsResponse.claims:type_name -> payment.Claim
	0, // 1: payment.PaymentService.RegisterService:input_type -> payment.RegisterRequest
	2, // 2: payment.PaymentService.SendHeartbeat:input_type -> payment.HeartbeatRequest
	4, // 3: payment.PaymentService.GetClaimsByStatus:input_type -> payment.StatusRequest
	7, // 4: payment.PaymentService.UpdateClaimPayment:input_type -> payment.PaymentUpdateRequest
	1, // 5: payment.PaymentService.RegisterService:output_type -> payment.RegisterResponse
	3, // 6: payment.PaymentService.SendHeartbeat:output_type -> payment.HeartbeatResponse
	6, // 7: payment.PaymentService.GetClaimsByStatus:output_type -> payment.ClaimsResponse
	8, // 8: payment.PaymentService.UpdateClaimPayment:output_type -> payment.PaymentUpdateResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
