services:
  camel-gateway:
    build:
      context: ./module-services/camel-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - claimant-services
      - employer-services
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - ui-modernization

  claimant-services:
    build:
      context: ./module-services/claimant-services
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/claimant_services
    depends_on:
      - mongodb
    networks:
      - ui-modernization

  employer-services:
    build:
      context: ./module-services/EmployerServices
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=employer_services;Uid=root;Pwd=employer_password;
      - CamelGateway__BaseUrl=http://camel-gateway:8080
      - CamelGateway__ServiceName=employer-services
      - CamelGateway__ServicePort=5002
      - CamelGateway__HeartbeatIntervalSeconds=30
      - Artemis__BrokerUrl=tcp://camel-gateway:61616
      - Artemis__Username=admin
      - Artemis__Password=admin
      - Artemis__TopicName=claim.events
    depends_on:
      - mysql
      - camel-gateway
    networks:
      - ui-modernization

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ui-modernization

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=employer_password
      - MYSQL_DATABASE=employer_services
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ui-modernization

volumes:
  mongodb_data:
  mysql_data:

networks:
  ui-modernization:
    driver: bridge