services:
  # API Gateway
  traefik:
    image: traefik:v2.5
    ports:
      - "80:80"      # Web traffic
      - "8080:8080"  # Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./module-services/api-gateway/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./module-services/api-gateway/traefik-dynamic-conf.yml:/etc/traefik/traefik-dynamic-conf.yml:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"

  # Protocol Conversion Middleware
  protocol-converter:
    build: ./module-services/api-gateway
    ports:
      - "3000:3000"
    environment:
      - CLAIMS_SERVICE_URL=http://claims-processing:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.converter.rule=PathPrefix(`/convert`)"
      - "traefik.http.routers.converter.entrypoints=web"
      - "traefik.http.services.converter.loadbalancer.server.port=3000"

  # API Gateway Dashboard
  gateway-dashboard:
    build: ./module-services/api-gateway/dashboard
    ports:
      - "3030:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=PathPrefix(`/gateway-dashboard`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.services.dashboard.loadbalancer.server.port=80"

  # Claimant Services
  claimant-services:
    build: ./module-services/claimant-services/server
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
      - protocol-converter
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/claimant
      - CONVERTER_URL=http://protocol-converter:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.claimant-graphql.rule=PathPrefix(`/graphql`)"
      - "traefik.http.routers.claimant-graphql.entrypoints=web"
      - "traefik.http.services.claimant-graphql.loadbalancer.server.port=4000"

  # Claimant UI
  claimant-ui:
    build: ./module-services/claimant-services/claimant
    ports:
      - "3001:80"
    depends_on:
      - claimant-services
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.claimant-ui.rule=PathPrefix(`/claimant`)"
      - "traefik.http.routers.claimant-ui.entrypoints=web"
      - "traefik.http.services.claimant-ui.loadbalancer.server.port=80"

  # Claims Processing
  claims-processing:
    build: ./module-services/claims-processing
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/claims
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.claims-api.rule=PathPrefix(`/api/claims`)"
      - "traefik.http.routers.claims-api.entrypoints=web"
      - "traefik.http.services.claims-api.loadbalancer.server.port=8000"

  # Claims Processing UI
  claims-ui:
    build: ./module-services/claims-processing/client
    ports:
      - "3002:80"
    depends_on:
      - claims-processing
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.claims-ui.rule=PathPrefix(`/processor`)"
      - "traefik.http.routers.claims-ui.entrypoints=web"
      - "traefik.http.services.claims-ui.loadbalancer.server.port=80"

  # Main UI (Landing Page)
  ui-demo:
    build: ./module-services/ui-demo
    ports:
      - "8081:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=PathPrefix(`/`)"
      - "traefik.http.routers.ui.entrypoints=web"
      - "traefik.http.services.ui.loadbalancer.server.port=80"

  # Databases
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=claims
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongodb-data:
  postgres-data:
