version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    depends_on:
      - business-rules-engine
      - claims-processing
      - employer-services
      - benefits-administration
    networks:
      - ui-modernization

  # Business Rules Engine
  business-rules-engine:
    build:
      context: ./business-rules-engine
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
    volumes:
      - ./business-rules-engine:/app
      - /app/node_modules
    networks:
      - ui-modernization

  # Claims Processing
  claims-processing:
    build:
      context: ./claims-processing
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=development
      - API_GATEWAY_URL=http://api-gateway:3000
    volumes:
      - ./claims-processing:/app
      - /app/node_modules
    depends_on:
      - api-gateway
    networks:
      - ui-modernization

  # Employer Services
  employer-services:
    build:
      context: ./employer-services
    ports:
      - "3003:3003"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - API_GATEWAY_URL=http://api-gateway:3000
    volumes:
      - ./employer-services:/app
    depends_on:
      - api-gateway
    networks:
      - ui-modernization

  # Benefits Administration
  benefits-administration:
    build:
      context: ./benefits-administration
    ports:
      - "3004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiGatewayUrl=http://api-gateway:3000
    volumes:
      - ./benefits-administration:/app
      - /app/obj
      - /app/bin
    depends_on:
      - api-gateway
    networks:
      - ui-modernization

  # Claimant Services Frontend
  claimant-services:
    build:
      context: ./claimant-services
    ports:
      - "3005:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api
    volumes:
      - ./claimant-services:/app
      - /app/node_modules
    depends_on:
      - api-gateway
    networks:
      - ui-modernization

networks:
  ui-modernization:
    driver: bridge