version: '3.8'

services:
  camel-gateway:
    build: ./module-services/camel-gateway
    ports:
      - "8080:8080"  # Main Camel routes
      - "8081:8081"  # Health dashboard
    environment:
      - CAMEL_HEALTH_CHECK_INTERVAL=30000
      - CAMEL_LOG_LEVEL=INFO
    volumes:
      - ./module-services/camel-gateway/routes:/opt/camel/routes
    networks:
      - camel-network

networks:
  camel-network:
    driver: bridge