services:
  camel-gateway:
    build:
      context: ./module-services/camel-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - claimant-services
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - ui-modernization
    restart: unless-stopped

  claimant-services:
    build:
      context: ./module-services/claimant-services
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/claimant_services
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - ui-modernization
    restart: unless-stopped

  employer-services:
    build:
      context: ./module-services/EmployerServices
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=employer_services;Uid=root;Pwd=employer_password;SslMode=none;AllowPublicKeyRetrieval=true;
      - CamelGateway__BaseUrl=http://camel-gateway:8080
      - CamelGateway__ServiceName=employer-services
      - CamelGateway__ServicePort=5002
      - CamelGateway__HeartbeatIntervalSeconds=30
      - ClaimPolling__IntervalSeconds=30
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ui-modernization
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ui-modernization
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=employer_password
      - MYSQL_DATABASE=employer_services
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ui-modernization
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pemployer_password"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

volumes:
  mongodb_data:
  mysql_data:

networks:
  ui-modernization:
    driver: bridge
