version: '3.8'

services:
  # Kong API Gateway
  kong:
    image: kong:alpine
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong/kong.yml:/kong/kong.yml
    networks:
      - ui-network

  # Business Rules Engine
  business-rules:
    build: ./business-rules
    ports:
      - "3001:3001"
    volumes:
      - ./business-rules/rules.json:/app/rules.json
    environment:
      - KONG_URL=https://scaling-space-chainsaw-q74644jjrrgrh4q54-8000.app.github.dev
    networks:
      - ui-network

  # Claimant Services (React)
  claimant-services:
    build: ./modules/claimant-services
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=https://scaling-space-chainsaw-q74644jjrrgrh4q54-8000.app.github.dev
    networks:
      - ui-network

  # Claims Processing (Node.js)
  claims-processing:
    build: ./modules/claims-processing
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - KONG_URL=https://scaling-space-chainsaw-q74644jjrrgrh4q54-8000.app.github.dev
      - RULES_ENGINE_URL=http://business-rules:3001
    networks:
      - ui-network

  # Employer Services (Python)
  employer-services:
    build: ./modules/employer-services
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - KONG_URL=https://scaling-space-chainsaw-q74644jjrrgrh4q54-8000.app.github.dev
    networks:
      - ui-network

  # Benefits Administration (C#)
  benefits-admin:
    build: ./modules/benefits-admin
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - KONG_URL=https://scaling-space-chainsaw-q74644jjrrgrh4q54-8000.app.github.dev
    networks:
      - ui-network

networks:
  ui-network:
    driver: bridge
