version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: ./modular-ui-system/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./modular-ui-system/api-gateway:/app
      - /app/node_modules
    networks:
      - ui-modernization

  # Business Rules Engine
  business-rules-engine:
    build:
      context: ./modular-ui-system/business-rules-engine
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
    volumes:
      - ./modular-ui-system/business-rules-engine:/app
      - /app/node_modules
    networks:
      - ui-modernization
    depends_on:
      - api-gateway

  # Claims Processing
  claims-processing:
    build:
      context: ./modular-ui-system/claims-processing
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=development
      - API_GATEWAY_URL=http://api-gateway:3000
    volumes:
      - ./modular-ui-system/claims-processing:/app
      - /app/node_modules
    networks:
      - ui-modernization
    depends_on:
      - api-gateway

  # Employer Services
  employer-services:
    build:
      context: ./modular-ui-system/employer-services
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - API_GATEWAY_URL=http://api-gateway:3000
    volumes:
      - ./modular-ui-system/employer-services:/app
    networks:
      - ui-modernization
    depends_on:
      - api-gateway

  # Benefits Administration
  benefits-administration:
    build:
      context: ./modular-ui-system/benefits-administration
      dockerfile: Dockerfile
    ports:
      - "3004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiGatewayUrl=http://api-gateway:3000
    volumes:
      - ./modular-ui-system/benefits-administration:/app
    networks:
      - ui-modernization
    depends_on:
      - api-gateway

  # Claimant Services Frontend
  claimant-services:
    build:
      context: ./modular-ui-system/claimant-services
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api
      - WDS_SOCKET_PORT=0
    volumes:
      - ./modular-ui-system/claimant-services:/app
      - /app/node_modules
    networks:
      - ui-modernization
    depends_on:
      - api-gateway

networks:
  ui-modernization:
    driver: bridge