version: '3.8'

services:
  # Traefik API Gateway
traefik:
  image: traefik:v2.9
  command:
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - "--entrypoints.web.address=:8000"
    - "--providers.docker.network=app-network"
  ports:
    - "8000:8000"  # API Gateway
    - "8080:8080"  # Traefik Dashboard
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    - app-network
  restart: always

  # Module Services
  claimant-services:
    build: ./Modules/claimant-services
    volumes:
      - ./Modules/claimant-services:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
    networks:
      - app-network
    restart: always

  claims-processing:
    build: ./Modules/claims-processing
    volumes:
      - ./Modules/claims-processing:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - API_GATEWAY_URL=http://traefik:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.claims.rule=PathPrefix(`/api/claims`)"
      - "traefik.http.services.claims.loadbalancer.server.port=3002"
    networks:
      - app-network
    restart: always

  employer-services:
    build: ./Modules/employer-services
    volumes:
      - ./Modules/employer-services:/app
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - API_GATEWAY_URL=http://traefik:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.employers.rule=PathPrefix(`/graphql`)"
      - "traefik.http.services.employers.loadbalancer.server.port=3003"
    networks:
      - app-network
    restart: always

  benefits-admin:
    build: ./Modules/benefits-admin
    ports:
      - "3004:3004"
    environment:
      - ASPNETCORE_URLS=http://+:3004
      - API_GATEWAY_URL=http://traefik:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.benefits.rule=PathPrefix(`/api/benefits`)"
      - "traefik.http.services.benefits.loadbalancer.server.port=3004"
    networks:
      - app-network
    restart: always

  business-rules:
    build: ./business-rules
    ports:
      - "3001:3001"
    volumes:
      - ./business-rules:/app
      - /app/node_modules
    environment:
      - PORT=3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rules.rule=PathPrefix(`/api/rules`)"
      - "traefik.http.services.rules.loadbalancer.server.port=3001"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
