services:
  camel-gateway:
    build:
      context: ./module-services/camel-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - claimant-services
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - ui-modernization
    restart: unless-stopped

  claimant-services:
    build:
      context: ./module-services/claimant-services
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/claimant_services
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - ui-modernization
    restart: unless-stopped

  employer-services:
    build:
      context: ./module-services/EmployerServices
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=employer_services;Uid=root;Pwd=employer_password;SslMode=none;AllowPublicKeyRetrieval=true;
      - CamelGateway__BaseUrl=http://camel-gateway:8080
      - CamelGateway__ServiceName=employer-services
      - CamelGateway__ServicePort=5002
      - CamelGateway__HeartbeatIntervalSeconds=30
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ui-modernization
    restart: unless-stopped

  tax-services:
    build:
      context: ./module-services/tax-services
    ports:
      - "5003:5003"
    environment:
      - DB_HOST=tax-postgres
      - DB_NAME=taxservices
      - DB_USER=postgres
      - DB_PASSWORD=tax_password
      - DB_PORT=5432
      - CAMEL_GATEWAY_URL=http://camel-gateway:8080
      - SERVICE_NAME=tax-services
      - PORT=5003
      - POLL_INTERVAL=10
    depends_on:
      tax-postgres:
        condition: service_healthy
      camel-gateway:
        condition: service_started
    networks:
      - ui-modernization
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ui-modernization
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=employer_password
      - MYSQL_DATABASE=employer_services
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ui-modernization
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pemployer_password"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  tax-postgres:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=taxservices
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tax_password
    volumes:
      - tax_postgres_data:/var/lib/postgresql/data
    networks:
      - ui-modernization
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taxservices"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  mongodb_data:
  mysql_data:
  tax_postgres_data:

networks:
  ui-modernization:
    driver: bridge