services:
  camel-gateway:
    build:
      context: ./module-services/camel-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - claimant-services
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - ui-modernization

  claimant-services:
    build:
      context: ./module-services/claimant-services
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/claimant_services
    depends_on:
      - mongodb
    networks:
      - ui-modernization

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ui-modernization

volumes:
  mongodb_data:

networks:
  ui-modernization:
    driver: bridge
