version: '3.8'

services:
  # Camel Gateway
  camel-gateway:
    build:
      context: ./module-services/camel-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - ui-modernization
    depends_on:
      - claimant-services
    environment:
      - CLAIMANT_SERVICE_URL=http://claimant-services:3000

  # Claimant Services
  claimant-services:
    build:
      context: ./module-services/claimant-services
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - ui-modernization
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/claimant_services

  # MongoDB for Claimant Services
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ui-modernization

networks:
  ui-modernization:

volumes:
  mongodb_data:
