name: Access Request
description: Request access to a GitHub repository
body:
  - type: input
    id: username
    attributes:
      label: GitHub Username
      placeholder: "Enter your email address"
    validations:
      required: true
  - type: dropdown
    id: repo
    attributes:
      label: Repository Requested
      options:
        - Open UI Framework
        - Repo B
        - Repo C
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason for Access
      description: "Briefly describe why you need access"
    validations:
      required: true
