# .devcontainer/docker-compose.yml
version: '3'
services:
  workspace:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:kong

  kong:
    image: kong:2.8.1-alpine
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
    volumes:
      - ../kong/kong.yml:/etc/kong/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"

  json-rules-engine:
    build: ../rules-engine
    ports:
      - "3001:3001"

  claimant-service:
    build: ../claimant-service
    ports:
      - "3000:3000"

  employer-service:
    build: ../employer-service
    ports:
      - "3002:3002"

  claims-processing:
    build: ../claims-processing
    ports:
      - "3003:3003"

  benefits-admin:
    build: ../benefits-admin
    ports:
      - "3004:3004"

  tax-admin:
    build: ../tax-admin
    ports:
      - "8080:8080"
